<a href="https://colab.research.google.com/github/yujiimt/python_ML/blob/master/pytorch/tutorial/pytorch_tutorial1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
from __future__ import print_function
import torch
import torch.nn as nn
import torch.nn.functional as F

In [2]:
#未初期化テンソル
x = torch.empty(5, 3)
print(x)

tensor([[7.0344e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 6.4460e-44],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [3]:
#乱数テンソル
x = torch.rand(5, 3)
print(x)

tensor([[0.4158, 0.5482, 0.2283],
        [0.5403, 0.0900, 0.5103],
        [0.2486, 0.6215, 0.1532],
        [0.3522, 0.0847, 0.4926],
        [0.0216, 0.7549, 0.8514]])


In [4]:
#零行列
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
#テンソルの定義
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[4.0232e-01, 4.5370e-01, 9.3877e-01],
        [5.7569e-01, 7.5556e-03, 5.4645e-02],
        [1.9795e-01, 3.8719e-02, 4.7059e-01],
        [4.0335e-01, 3.8139e-01, 5.3737e-01],
        [7.7981e-04, 8.2307e-01, 3.6951e-01]])


In [8]:
x.dtype

torch.float32

In [9]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [10]:
x = torch.rand_like(x, dtype=torch.float)
print(x)

tensor([[0.6691, 0.4369, 0.1179],
        [0.3230, 0.1894, 0.8744],
        [0.3453, 0.2840, 0.2666],
        [0.3843, 0.3813, 0.9746],
        [0.8351, 0.1934, 0.8016]])


In [11]:
print(x.size())

torch.Size([5, 3])


In [12]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)
print(x)
print(y)

tensor([[0.9088, 0.1110, 0.2775],
        [0.9242, 0.2667, 0.3016],
        [0.4252, 0.2294, 0.3298],
        [0.0946, 0.3992, 0.2445],
        [0.1305, 0.3915, 0.4796]])
tensor([[0.1557, 0.1805, 0.7292],
        [0.6622, 0.7578, 0.2822],
        [0.9170, 0.4606, 0.6055],
        [0.6050, 0.7265, 0.1474],
        [0.1797, 0.0484, 0.9803]])


In [13]:
print(x+y)

tensor([[1.0645, 0.2915, 1.0066],
        [1.5864, 1.0244, 0.5837],
        [1.3422, 0.6900, 0.9353],
        [0.6996, 1.1257, 0.3919],
        [0.3102, 0.4399, 1.4599]])


In [14]:
torch.add(x,y)

tensor([[1.0645, 0.2915, 1.0066],
        [1.5864, 1.0244, 0.5837],
        [1.3422, 0.6900, 0.9353],
        [0.6996, 1.1257, 0.3919],
        [0.3102, 0.4399, 1.4599]])

In [15]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)

tensor([[1.0645, 0.2915, 1.0066],
        [1.5864, 1.0244, 0.5837],
        [1.3422, 0.6900, 0.9353],
        [0.6996, 1.1257, 0.3919],
        [0.3102, 0.4399, 1.4599]])

In [16]:
y.add(x)

tensor([[1.0645, 0.2915, 1.0066],
        [1.5864, 1.0244, 0.5837],
        [1.3422, 0.6900, 0.9353],
        [0.6996, 1.1257, 0.3919],
        [0.3102, 0.4399, 1.4599]])

In [17]:
# テンソルの計算過程を記録する
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [21]:
y = torch.rand(2,2)
z = torch.add(x, y)

In [22]:
print(z.grad_fn)

In [23]:
out = z * z * 3
result = out.mean()

In [24]:
print(out, result)

tensor([[6.5261, 9.0725],
        [3.8372, 4.1247]], grad_fn=<MulBackward0>) tensor(5.8901, grad_fn=<MeanBackward0>)


In [25]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)

False


In [26]:
a.requires_grad_(True)

tensor([[ 1.5220, -6.7775],
        [ 0.8128, -0.9636]], requires_grad=True)

In [27]:
print(a.requires_grad)

True


In [28]:
b = (a * a).sum()
print(b.grad_fn)

In [29]:
print(result)

tensor(5.8901, grad_fn=<MeanBackward0>)


In [31]:
result.backward()

In [32]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [33]:
print(x.grad)

tensor([[2.2124, 2.6085],
        [1.6964, 1.7588]])


In [34]:
x = torch.randn(3, requires_grad=True)
y = x * 2
while y.data.norm() < 1000:
  y = y * 2
print(y)

tensor([-129.0565, 1641.8359, -763.0583], grad_fn=<MulBackward0>)


In [35]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)
print(x.grad)

tensor([2.0480e+02, 2.0480e+03, 2.0480e-01])


In [36]:
print(x.requires_grad)


True


In [42]:
class Net(nn.Module):

  def __init__(self):
    super(Net, self).__init__()
    # 1 input image channel, 6 output channels, 3x3 square convolution
    # kernel
    self.conv1 = nn.Conv2d(1, 6, 3)
    self.conv2 = nn.Conv2d(6, 16, 3)
    # an affine operation: y = Wx + b
    self.fc1 = nn.Linear(16 * 6 * 6, 120)
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)
  
  def forward(self, x):
    #max pooling over a (2, 2) window
    x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
    # if the size is a square you can only specify a single numble
    x = F.max_pool2d(F.relu(self.conv2(x)), 2)
    x = x.view(-1, self.num_flat_features(x))
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x

  def num_flat_features(self, x):
    size = x.size()[1:]
    num_features = 1
    for s in size:
      num_features *= s
    return num_features

In [43]:
net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [44]:
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

tensor([[-0.0932, -0.1346, -0.0097,  0.0389,  0.0244,  0.1301, -0.2005,  0.0438,
          0.0561,  0.0093]], grad_fn=<AddmmBackward>)


In [45]:
net.zero_grad()
out.backward(torch.randn(1, 10))

In [46]:
# 損失関数　
output = net(input)
target = torch.randn(10)
target = target.view(1, -1)
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(1.1432, grad_fn=<MseLossBackward>)


In [47]:
# backprop

#勾配を0に
net.zero_grad()

print("conv1.bias.grad before backward")
print(net.conv1.bias.grad)
#逆伝播前のconv1の勾配

loss.backward()
#逆伝播

print("conv1.bias.grad.after backward")
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad.after backward
tensor([ 0.0092, -0.0090, -0.0134, -0.0083,  0.0287,  0.0084])


In [48]:
# weight = weight - learning_rate * gradient
learning_rate = 0.01
for f in net.parameters():
  f.data.sub_(f.grad.data * learning_rate)

In [49]:
#最適化のアルゴリズムを使う場合
import torch.optim as optim

#最適化アルゴリズムの作成
optimizer = optim.SGD(net.parameters(), lr=0.01)

#in your training loop
optimizer.zero_grad()
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()