In [1]:
import numpy as np

In [4]:
w = np.array([ [5.0], [3.0]])
x = np.array([ [1.0, 5.0]])

zeros = np.zeros([1,5])
ones = np.ones([1,5])

In [5]:
w

array([[5.],
       [3.]])

In [7]:
x

array([[1., 5.]])

In [8]:
zeros

array([[0., 0., 0., 0., 0.]])

In [9]:
ones

array([[1., 1., 1., 1., 1.]])

In [10]:
#一様分布、正規分布に従ってランダムに生成
uniform = np.random.rand(1,5)

normal = np.random.normal(size=[1,5])

In [11]:
uniform

array([[0.56015562, 0.83794218, 0.89775028, 0.99615876, 0.76644129]])

In [12]:
normal

array([[-0.0064534 , -0.52609751, -0.9288304 ,  0.37919497, -0.02396856]])

In [15]:
#内積の計算
xw = np.matmul(x,w)
print(xw)

#w のノルムの計算
ww = np.matmul(w.T, w)
print(ww)

[[20.]]
[[34.]]


In [17]:
X = np.array([ [1.0, 2.0], [2.0, 4.0], [3.0, 6.0] ])
print(X)
print("-"*15)
#1行2列の取り出し（行ベクトル）
Xrow1 = X[[0], :]
print(Xrow1)
print("-"*15)

#3行１列の取り出し（列ベクトル）
Xrow2 =X[:, [1]]
print(Xrow2)

[[1. 2.]
 [2. 4.]
 [3. 6.]]
---------------
[[1. 2.]]
---------------
[[2.]
 [4.]
 [6.]]


In [20]:
b = np.array([[1.0], [1.0], [1.0]])

#行列とベクトルの積と和
res = np.matmul(X, w) + b
print(res)

[[12.]
 [23.]
 [34.]]


In [23]:
A = np.array([ [6.0, 2.0 ],  [2.0, 5.0]])
B = np.array( [[6.0, 3.0], [2.0, 1.0]])

#行列のランクの計算
rankA = np.linalg.matrix_rank(A)
rankB = np.linalg.matrix_rank(B)

print(f"rankA{rankA}")
print(f"rankB{rankB}")


#Aの逆行列
if rankA == len(A):
    invA = np.linalg.inv(A)
    print(f"行列A）ランク:{rankA}\n逆行列:\n{invA}\n")
else:
    print(f"行列A）ランク:{rankA},特異行列\n")
    
#Bの逆行列
if rankB == len(B):
    invB = np.linalg.inv(B)
    print(f"行列B）ランク:{rankB}\n逆行列:\n{invB}\n")
else:
    print(f"行列B）ランク:{rankB},特異行列\n")

rankA2
rankB1
行列A）ランク:2
逆行列:
[[ 0.19230769 -0.07692308]
 [-0.07692308  0.23076923]]

行列B）ランク:1,特異行列



In [24]:
#行列式
detA = np.linalg.det(A)
print(detA)
detB = np.linalg.det(B)
print(detB)

25.99999999999999
0.0


In [27]:
#固有値問題
A = np.array([[3,2], [4, 1]])


# 固有値問題の解
L , V = np.linalg.eig(A)

print(f"行列Aの固有値:\n{L}\n")

print(f"行列Aの固有ベクトル:\n{V}\n")

print(f"固有ベクトルの内積:{np.matmul(V[:,[0]].T,V[:,[1]])}\n")

print(f"固有値の和:{np.sum(L)}\n")

print(f"行列Aのトレース（対角成分の和）:{np.sum(np.diag(A))}\n")

print(f"固有値の積:{np.prod(L)}\n")

print(f"行列Aの行列式:{np.linalg.det(A):.1f}\n")

print(f"行列Vの逆行列:\n{np.linalg.inv(V)}\n")

print(f"行列Vの転置:\n{V.T}\n")

行列Aの固有値:
[ 5. -1.]

行列Aの固有ベクトル:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]

固有ベクトルの内積:[[0.31622777]]

固有値の和:4.0

行列Aのトレース（対角成分の和）:4

固有値の積:-5.0

行列Aの行列式:-5.0

行列Vの逆行列:
[[ 0.94280904  0.47140452]
 [-0.74535599  0.74535599]]

行列Vの転置:
[[ 0.70710678  0.70710678]
 [-0.4472136   0.89442719]]



In [29]:
A = np.array([ [2, -3],  [4, 1]])

b = np.array([ [5], [-2]])



#行列式が非ゼロか否かを確認
if np.linalg.det(A) != 0:
    # Aの逆行列とベクトルbの積から解を求める
    w = np.matmul(np.linalg.inv(A), b)
    print(f"wの解{w}")
else:
    print("解が存在しません")

wの解[[-0.07142857]
 [-1.71428571]]


In [30]:
#学習率の設定
alpha = 0.2

#パラメーターの初期化
w = 1


for ite in range(50):
    print(f"反復: {ite}, w={round(w, 2):.2f}")
    
    #最急降下法によるパラメーターの更新
    w -= alpha * 3 * w**2

反復: 0, w=1.00
反復: 1, w=0.40
反復: 2, w=0.30
反復: 3, w=0.25
反復: 4, w=0.21
反復: 5, w=0.18
反復: 6, w=0.16
反復: 7, w=0.15
反復: 8, w=0.13
反復: 9, w=0.12
反復: 10, w=0.11
反復: 11, w=0.11
反復: 12, w=0.10
反復: 13, w=0.09
反復: 14, w=0.09
反復: 15, w=0.08
反復: 16, w=0.08
反復: 17, w=0.08
反復: 18, w=0.07
反復: 19, w=0.07
反復: 20, w=0.07
反復: 21, w=0.06
反復: 22, w=0.06
反復: 23, w=0.06
反復: 24, w=0.06
反復: 25, w=0.06
反復: 26, w=0.05
反復: 27, w=0.05
反復: 28, w=0.05
反復: 29, w=0.05
反復: 30, w=0.05
反復: 31, w=0.05
反復: 32, w=0.04
反復: 33, w=0.04
反復: 34, w=0.04
反復: 35, w=0.04
反復: 36, w=0.04
反復: 37, w=0.04
反復: 38, w=0.04
反復: 39, w=0.04
反復: 40, w=0.04
反復: 41, w=0.04
反復: 42, w=0.03
反復: 43, w=0.03
反復: 44, w=0.03
反復: 45, w=0.03
反復: 46, w=0.03
反復: 47, w=0.03
反復: 48, w=0.03
反復: 49, w=0.03


In [31]:
# p = 6 / 13 (青色のボールの確率)のベルヌーイ分布に従って１０回試行を行う

X1 = np.random.binomial(1, 6/13, 10)
X2 = np.random.binomial(1, 6/13, 10)
X3 = np.random.binomial(1, 6/13, 10)


print(f"データX1:\n{X1}")
print(f"データX2:\n{X2}")
print(f"データX3:\n{X3}")

データX1:
[1 0 0 1 0 0 1 0 0 0]
データX2:
[0 0 0 1 0 0 1 0 0 1]
データX3:
[0 0 0 0 1 0 0 1 1 0]


In [ ]:
# 正規分布に従ったランダ

#平均０、分散１の正規分布に従って１０回試行を行う
X1 = np.random.normal(0, 1, 10)


#平均3,分散１の正規分布に従って１０回試行を行う
X2 = np.random.normal(3, 1,  10)


#平均-3、ぶんさいn